from __future__ import annotations
import json, sqlite3
from bdb_vnext.m4a_read_query import ReadOnlyWorkKernelQuery

def _database() -> sqlite3.Connection:
    connection = sqlite3.connect(":memory:")
    connection.executescript("""CREATE TABLE m4a_work_items (work_id TEXT PRIMARY KEY,task_id TEXT,kind TEXT,disposition TEXT,state_version INTEGER,created_order INTEGER,updated_order INTEGER,created_at REAL,updated_at REAL); CREATE TABLE m4a_runs (run_id TEXT PRIMARY KEY,work_id TEXT,status TEXT,outcome TEXT,effect_certainty TEXT,lease_id TEXT,fence INTEGER,started_order INTEGER,ended_order INTEGER); CREATE TABLE m4a_waits (wait_id TEXT PRIMARY KEY,work_id TEXT,reason TEXT,status TEXT,created_order INTEGER,resolved_order INTEGER,resolution TEXT); CREATE TABLE m4a_leases (work_id TEXT PRIMARY KEY,lease_id TEXT,owner_id TEXT,fence INTEGER,state TEXT,acquired_at REAL,expires_at REAL); CREATE TABLE m4a_resource_claims (resource_key TEXT PRIMARY KEY,work_id TEXT,lease_id TEXT,fence INTEGER,state TEXT,claimed_order INTEGER); CREATE TABLE m4a_transition_facts (fact_id TEXT PRIMARY KEY,work_id TEXT,state_version INTEGER,kind TEXT,from_disposition TEXT,to_disposition TEXT,causal_digest TEXT,payload BLOB,created_order INTEGER);""")
    return connection

def test_read_adapter_recreates_canonical_work_query_without_mutation() -> None:
    c = _database(); c.execute("INSERT INTO m4a_work_items VALUES (?,?,?,?,?,?,?,?,?)", ("w1","t1","engineering","WAITING",3,1,4,10.0,20.0)); c.execute("INSERT INTO m4a_runs VALUES (?,?,?,?,?,?,?,?,?)", ("r1","w1","ACTIVE",None,"POSSIBLE","l1",2,2,None)); c.execute("INSERT INTO m4a_waits VALUES (?,?,?,?,?,?,?)", ("wait1","w1","validation","OPEN",3,None,None)); c.execute("INSERT INTO m4a_leases VALUES (?,?,?,?,?,?,?)", ("w1","l1","worker",2,"ACTIVE",1.0,100.0)); c.execute("INSERT INTO m4a_resource_claims VALUES (?,?,?,?,?,?)", ("repo:test","w1","l1",2,"HELD",2)); c.execute("INSERT INTO m4a_transition_facts VALUES (?,?,?,?,?,?,?,?,?)", ("f1","w1",3,"wait_opened","RUNNING","WAITING","sha256:"+"a"*64,json.dumps({"wait_id":"wait1"}).encode(),4)); before = c.total_changes
    query = ReadOnlyWorkKernelQuery(c, clock=lambda: 50.0).query("w1"); assert query is not None; document = query.as_dict(); assert document["authority"] == "devmaster.bdb.vnext.work-kernel"; assert document["work"]["work_id"] == "w1"; assert document["active_run"]["run_id"] == "r1"; assert document["active_wait"]["wait_id"] == "wait1"; assert document["lease"]["state"] == "ACTIVE"; assert document["resource_claim"]["resource_key"] == "repo:test"; assert document["recent_facts"][0]["kind"] == "wait_opened"; assert "query_digest" in document; assert c.total_changes == before

def test_catalog_uses_one_time_basis_for_lease_projection() -> None:
    c = _database(); c.execute("INSERT INTO m4a_work_items VALUES (?,?,?,?,?,?,?,?,?)", ("w1","t1","engineering","READY",0,1,1,1.0,1.0)); c.execute("INSERT INTO m4a_leases VALUES (?,?,?,?,?,?,?)", ("w1","l1","worker",1,"ACTIVE",1.0,5.0)); ticks = iter((4.0,99.0,100.0)); queries = ReadOnlyWorkKernelQuery(c, clock=lambda: next(ticks)).catalog(limit=10); assert len(queries) == 1; assert queries[0].lease is not None; assert queries[0].lease.state == "ACTIVE"
