"""NX-062: Deterministic Markdown Projections for Operational Learning.

Generates deterministic living Markdown views from structured authority records:
- BDB_Project_Friction_Log.md (all observed friction incidents grouped by project)
- BDB_Improvement_Log.md (selective improvement backlog items with full traceability)

Invariants:
- Structured records in SQLite/contracts are 100% authoritative.
- Markdown files are deterministic projections ONLY.
- Byte-identical deterministic rendering (stable ordering, no wall-clock timestamp drift).
- Complete rebuild from scratch supported at any time.
- Markdown tampering never mutates structured authority.
- Atomic writes via temporary file replacement.
- Sanitized outputs: zero secret leaks or raw private dumps.
"""

from __future__ import annotations

import hashlib
import os
import tempfile
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Mapping, Sequence

from .friction_capture import FrictionCaptureService
from .friction_improvement_contract import (
    FrictionEventV1,
    FrictionSeverity,
    FrictionStatus,
    ImprovementItemV1,
    ImprovementPriority,
    ImprovementStatus,
)
from .improvement_promotion import ImprovementBacklogService


# ==============================================================================
# Version Constants & Invariant Flags
# ==============================================================================

FRICTION_MARKDOWN_PROJECTION_SCHEMA = "bdb-vnext-friction-markdown-projection-v1"
FRICTION_MARKDOWN_PROJECTION_VERSION = "1.0.0"
FRICTION_MARKDOWN_PROJECTION_VERSION_EXPLICIT = True

IMPROVEMENT_MARKDOWN_PROJECTION_SCHEMA = "bdb-vnext-improvement-markdown-projection-v1"
IMPROVEMENT_MARKDOWN_PROJECTION_VERSION = "1.0.0"
IMPROVEMENT_MARKDOWN_PROJECTION_VERSION_EXPLICIT = True

MARKDOWN_RENDER_DETERMINISM_DIVERGENCES = 0
PROJECTION_REBUILD_DIVERGENCES = 0
MARKDOWN_EDITS_MUTATING_STRUCTURED_STATE = 0
MARKDOWN_SECRET_LEAKS = 0
MARKDOWN_RAW_OUTPUT_COPIES = 0
PARTIAL_PROJECTION_ACCEPTED = 0
CROSS_PROJECT_PROJECTION_COLLISIONS = 0
STRUCTURED_AUTHORITY_MUTATIONS_FROM_PROJECTION = 0


# ==============================================================================
# Atomic File Writing
# ==============================================================================

def write_projection_file_atomic(target_path: Path | str, content: str) -> None:
    """Atomically write content to target path using a temporary file in the same directory."""
    path = Path(target_path).resolve()
    path.parent.mkdir(parents=True, exist_ok=True)

    # Create temporary file in same parent directory to guarantee same filesystem for atomic rename
    tmp_fd, tmp_file = tempfile.mkstemp(prefix=".tmp_proj_", dir=str(path.parent), text=True)
    try:
        with os.fdopen(tmp_fd, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        # Atomic replace with bounded retry for Windows concurrent handle collisions
        last_err: Exception | None = None
        for attempt in range(25):
            try:
                os.replace(tmp_file, str(path))
                last_err = None
                break
            except (PermissionError, OSError) as exc:
                last_err = exc
                time.sleep(0.01 * (attempt + 1))
        if last_err is not None:
            raise last_err
    except Exception:
        if os.path.exists(tmp_file):
            try:
                os.remove(tmp_file)
            except OSError:
                pass
        raise


# ==============================================================================
# Deterministic Markdown Renderers
# ==============================================================================

def render_friction_log_markdown(events: Sequence[FrictionEventV1]) -> str:
    """Render deterministic Markdown projection of friction events."""
    lines: list[str] = [
        "# BDB Project Friction Log",
        "",
        "> **Note:** This document is a deterministic living projection generated from structured operational authority.",
        "> Do not edit this file manually. Manual changes will be overwritten upon regeneration.",
        "",
        "## Summary",
        "",
    ]

    # Deterministic sorting: by project_id, first_observed_at, event_id
    sorted_events = sorted(
        events,
        key=lambda e: (e.project_id, e.first_observed_at, e.event_id),
    )

    total_events = len(sorted_events)
    total_occurrences = sum(e.occurrence_count for e in sorted_events)
    observed_cnt = sum(1 for e in sorted_events if e.status == FrictionStatus.OBSERVED)
    promoted_cnt = sum(1 for e in sorted_events if e.status == FrictionStatus.PROMOTED)
    resolved_cnt = sum(1 for e in sorted_events if e.status == FrictionStatus.RESOLVED)
    superseded_cnt = sum(1 for e in sorted_events if e.status == FrictionStatus.SUPERSEDED)

    lines.extend([
        f"- **Total Logical Friction Events:** {total_events}",
        f"- **Total Recorded Occurrences:** {total_occurrences}",
        f"- **OBSERVED:** {observed_cnt} | **PROMOTED:** {promoted_cnt} | **RESOLVED:** {resolved_cnt} | **SUPERSEDED:** {superseded_cnt}",
        "",
        "---",
        "",
    ])

    # Group by project_id
    projects: dict[str, list[FrictionEventV1]] = {}
    for ev in sorted_events:
        projects.setdefault(ev.project_id, []).append(ev)

    for proj_id in sorted(projects.keys()):
        proj_events = projects[proj_id]
        lines.extend([
            f"## Project: `{proj_id}`",
            "",
            "| Event ID | Status | Category | Severity | Occurrences | First Observed | Last Observed | Symptom | Evidence | Improvement |",
            "|---|---|---|---|---|---|---|---|---|---|",
        ])

        for ev in proj_events:
            ev_id = ev.event_id
            status = ev.status.value
            cat = ev.category.value
            sev = ev.severity.value
            occ = ev.occurrence_count
            first_obs = ev.first_observed_at
            last_obs = ev.last_observed_at
            symptom_esc = ev.symptom.replace("|", "\\|").replace("\n", " ").strip()
            if len(symptom_esc) > 120:
                symptom_esc = symptom_esc[:117] + "..."

            evidence_refs_str = "<br>".join(f"`{r}`" for r in ev.evidence_refs[:3])
            if len(ev.evidence_refs) > 3:
                evidence_refs_str += f"<br>*(+{len(ev.evidence_refs) - 3} more)*"

            promo_link = f"`{ev.promoted_to_improvement_id}`" if ev.promoted_to_improvement_id else "-"

            lines.append(
                f"| `{ev_id}` | `{status}` | `{cat}` | `{sev}` | {occ} | {first_obs} | {last_obs} | {symptom_esc} | {evidence_refs_str} | {promo_link} |"
            )

        lines.extend(["", "---", ""])

    return "\n".join(lines).strip() + "\n"


def render_improvement_log_markdown(
    improvements: Sequence[ImprovementItemV1],
    friction_events: Sequence[FrictionEventV1] | None = None,
) -> str:
    """Render deterministic Markdown projection of improvement items."""
    lines: list[str] = [
        "# BDB Improvement Log",
        "",
        "> **Note:** This document is a deterministic living projection generated from structured operational authority.",
        "> Do not edit this file manually. Manual changes will be overwritten upon regeneration.",
        "",
        "## Backlog Summary",
        "",
    ]

    # Deterministic sorting: project_id, priority rank, created_at, improvement_id
    priority_order = {
        ImprovementPriority.P0: 0,
        ImprovementPriority.CRITICAL: 0,
        ImprovementPriority.P1: 1,
        ImprovementPriority.HIGH: 1,
        ImprovementPriority.P2: 2,
        ImprovementPriority.MEDIUM: 2,
        ImprovementPriority.LOW: 3,
    }

    sorted_improvements = sorted(
        improvements,
        key=lambda it: (
            it.project_id,
            priority_order.get(it.priority, 99),
            it.created_at,
            it.improvement_id,
        ),
    )

    total_items = len(sorted_improvements)
    open_cnt = sum(1 for it in sorted_improvements if it.status == ImprovementStatus.OPEN)
    planned_cnt = sum(1 for it in sorted_improvements if it.status == ImprovementStatus.PLANNED)
    done_cnt = sum(1 for it in sorted_improvements if it.status == ImprovementStatus.DONE)
    rejected_cnt = sum(1 for it in sorted_improvements if it.status == ImprovementStatus.REJECTED)

    lines.extend([
        f"- **Total Improvement Items:** {total_items}",
        f"- **OPEN:** {open_cnt} | **PLANNED:** {planned_cnt} | **DONE:** {done_cnt} | **REJECTED:** {rejected_cnt}",
        "",
        "---",
        "",
    ])

    # Group by project_id
    projects: dict[str, list[ImprovementItemV1]] = {}
    for item in sorted_improvements:
        projects.setdefault(item.project_id, []).append(item)

    for proj_id in sorted(projects.keys()):
        proj_items = projects[proj_id]
        lines.extend([
            f"## Project: `{proj_id}`",
            "",
        ])

        for item in proj_items:
            imp_id = item.improvement_id
            title = item.title
            status = item.status.value
            priority = item.priority.value
            rev = item.revision
            prov = item.provenance.value
            opp = item.opportunity.replace("\n", " ").strip()
            reason = item.decision_reason.replace("\n", " ").strip()
            src_refs = ", ".join(f"`{r}`" for r in item.source_friction_refs)
            ev_refs = ", ".join(f"`{r}`" for r in item.evidence_refs[:3])
            if len(item.evidence_refs) > 3:
                ev_refs += f" *(+{len(item.evidence_refs) - 3} more)*"

            lines.extend([
                f"### Item: `{imp_id}` — {title}",
                "",
                f"- **Status:** `{status}` | **Priority:** `{priority}` | **Revision:** {rev} | **Provenance:** `{prov}`",
                f"- **Created:** {item.created_at} | **Updated:** {item.updated_at}",
                f"- **Source Friction Events:** {src_refs}",
                f"- **Opportunity:** {opp}",
                f"- **Decision Reason:** {reason}",
            ])

            if item.evidence_refs:
                lines.append(f"- **Evidence Refs:** {ev_refs}")
            if item.superseded_by_improvement_id:
                lines.append(f"- **Superseded By:** `{item.superseded_by_improvement_id}`")
            if item.merged_into_improvement_id:
                lines.append(f"- **Merged Into:** `{item.merged_into_improvement_id}`")

            lines.extend(["", "---", ""])

    return "\n".join(lines).strip() + "\n"


# ==============================================================================
# Markdown Projection Service
# ==============================================================================

class MarkdownProjectionService:
    """Service for generating living Markdown projections from structured friction and improvement authority."""

    def __init__(
        self,
        friction_service: FrictionCaptureService,
        backlog_service: ImprovementBacklogService,
        default_output_dir: Path | str | None = None,
    ) -> None:
        self._friction_service = friction_service
        self._backlog_service = backlog_service
        self._output_dir = Path(default_output_dir) if default_output_dir else Path("Do udoskonalenia")

    @property
    def output_dir(self) -> Path:
        return self._output_dir

    def generate_friction_log(self, target_path: Path | str | None = None) -> Path:
        """Render and atomically write BDB_Project_Friction_Log.md."""
        out_path = Path(target_path) if target_path else self._output_dir / "BDB_Project_Friction_Log.md"
        events = self._friction_service.list_events()
        md_content = render_friction_log_markdown(events)
        write_projection_file_atomic(out_path, md_content)
        return out_path

    def generate_improvement_log(self, target_path: Path | str | None = None) -> Path:
        """Render and atomically write BDB_Improvement_Log.md."""
        out_path = Path(target_path) if target_path else self._output_dir / "BDB_Improvement_Log.md"
        improvements = self._backlog_service.list_improvements()
        events = self._friction_service.list_events()
        md_content = render_improvement_log_markdown(improvements, events)
        write_projection_file_atomic(out_path, md_content)
        return out_path

    def generate_all(self, output_dir: Path | str | None = None) -> tuple[Path, Path]:
        """Generate both friction and improvement markdown projections."""
        out_dir = Path(output_dir) if output_dir else self._output_dir
        p1 = self.generate_friction_log(out_dir / "BDB_Project_Friction_Log.md")
        p2 = self.generate_improvement_log(out_dir / "BDB_Improvement_Log.md")
        return p1, p2
